### ISSUE TITLE
XDEBUG is not enabled in CLI

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#129]
Not sure if this is on purpose, but XDebug IS enabled for apache and FPM, but not for CLI php. `xdebug.ini` file is missing in `/etc/php5/cli/conf.d` dir.

Manually copying `xdebug.ini` file from FPM config to CLI config solves this issue.

If there is a config variable that needs to be added to bettbox'es config, please state it her and I will try to submit documentation PR about it.

**Comment by thom8** [comment]
@alexdesignworks it is disabled by default -- https://github.com/drupalmel/beetbox/blob/master/provisioning/ansible/beetbox.config.yml#L223

You can add `php_xdebug_cli_enable: 1` to your config file to enable it.

**Comment by AlexSkrypnyk** [comment]
Added description of configuration from used roles in #132
