### ISSUE TITLE
Offline provisioning is broken

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#138]
Offline provisioning, which was previously working, is now broken.

The offending task is **Get software for Python-based control.**, which to be fair, doesn't exactly sound like an essential task.

Looking further into the issue.

**Comment by thom8** [comment]
We should first determine if this task is a requirement for normal provisioning.
AFAIK `python-httplib2` is only required for `beetbox-tests`, so therefore could be moved there and only run on circle.

If the task is required, we then need to work out which package is getting removed in the clean up.

Debugging process: disable provisioning in Vagrantfile, bring up new VM, manually apt-get these packages until you find the one which is not installed.

Once identified - we will then need to work out which clean up task is removing this package -- https://github.com/beetboxvm/beetbox/blob/master/provisioning/packer/scripts/minimize.sh

**Comment by Decipher** [comment]
Ideally that tasks should only be run if `{{ beet_home }}/.beetbox/installed` doesn't exist, or more ideal, if the packages don't exist.

The current placement of the task means that if the first condition (`{{ beet_home }}/.beetbox/installed`) was implemented it would never run at all, so it would need to move.

I'd move it myself, but as I'm unaware of the reasoning for its current location it's probably best to determine exactly why it's there first.

**Comment by Decipher** [comment]
Also, the cleanup task isn't removing them, the `apt` module just doesn't care that they are there, it still insists on connecting to the Internet even without the need to do so.

**Comment by thom8** [comment]
minimize.sh is still removing `php-apc` -- https://circleci.com/gh/beetboxvm/beetbox/156

This script has been added to the circle build so we can see which packages are getting removed.
