### ISSUE TITLE
www dir location

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#14]
In Ubuntu, the default location for `www` dir is `/var/www`, but beetbox uses `/www`.

Can beetbox use `/var/www` so that web documents would be in expected location.

**Comment by thom8** [comment]
This is intentionally abstracted so that your synced folders don't conflict with existing sites, you can change this in the `Vagrantfile` if you want.

**Comment by AlexSkrypnyk** [comment]
I'm afraid it is not as simple as changing in `Vagrantfile`. For example, `beetbox.config.yml` has a line that relies on `/www` location.

> your synced folders don't conflict with existing sites
> no sure which 'existing sites' you mean. I though the only sites are the ones that we install with drupal role or manual.

So, currently, there is a `/www` and `/var/www` directories in Ubuntu box? This seems to be even more confusing.

**Comment by thom8** [comment]
You'd just need to override all references to the path in `beetbox.config.yml` from your config file.
This is fine if you know there's nothing else using this path.

I still believe we shouldn't use this path by default has the potential to conflict with extra packages -  https://github.com/thom8/beetbox/blob/master/ansible/beetbox.config.yml#L92

**Comment by Decipher** [comment]
What about using a /beetbox or /var/beetbox directory to reduce the likelihood of conflict?

**Comment by thom8** [comment]
`/beetbox` is already in use by the provisioner, but we could make this another config variable? however by default it shouldn't conflict with an existing path.

**Comment by AlexSkrypnyk** [comment]
I've been using beetbox for a while now and I'm still confused about the directories locations. This is how I see the directories structure:

`/beetbox` - all config for beetbox development stuff. `ansible` or `.beetbox` dir on the host machine can be mapped here if `beet_debug` is enabled, or it simply holds all beetbox config for provisioning

`/www` - cetralised location for all projects that a box will host. By default, there is only 1 project (see below). This cannot be `/var/www` as it may conflict with another services (see Thom's comment above)

`/www/beetbox` or `/www/app` - project dir from host machine is linked here. If project root is a web docroot, the vhost will be pointing here.

`/www/beetbox/docroot` or `/www/beetbox/web`\- docroot directory to use in vhost if project's docroot is deeper than project root. I like 'web` name as it is what symfony project use.

Now, these are the actual locations and I know that there are already variables that handle this. The problem I have is that those variables may not cover all these cases and that there is no documentation even to get the understanding of those variables (having a comment in `config.yml` will be enough for now). 

Another major problem is that these variables are very tightly coupled with a source code and changing a any location may fully brake the box. I have spent about a day on this, but decided to leave everything default. I understand that a new issue should be created about this, I but I could not provide many details as variable names and locations are too confusing.

**Comment by thom8** [comment]
@alexdesignworks apologies for any confusion caused but you should understand that we are still actually defining the way this will work (refer to the project status in the readme).

The only variable you should be concerned about is `beet_root` and at this stage it must be prefixed with the `/www` but we'll work or removing this requirement.

By default `beet_web` is the same as `beet_root` so you only need to modify this if your docroot happens to be a subdirectory of the project root.

I'm still a bit confused as to why this is a requirement as it would mean you had a dependency on a hardcoded absolute path inside your project, a default Drupal project should work in any location.

**Comment by AlexSkrypnyk** [comment]
@thom8 Thanks for the explanation. 
#63 has some changes to default directories locations (`/var/beetbox`) that suppress any discussions in this issue. For the sake of removing any confusion, I'm closing this one.

**Comment by AlexSkrypnyk** [comment]
Also, there is a similar discussion happens in #47
