### ISSUE TITLE
Add support for other supported databases

### ISSUE THREAD

**Issue by mradcliffe** [beetboxvm/beetbox#181]
It would be nice to have PostgreSQL and SQLite setup or available as options.

**Comment by thom8** [comment]
You can use SQLite by including `php5-sqlite` to `php_packages`

eg. add the following to `config.yml`

```
php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-intl
  - php-pear
  - php-apc
  - libpcre3-dev
  - php5-sqlite
```

Would be happy to add this to the defaults if someone wants to create a PR -- https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/config/beetbox.config.yml#L229-L242

PostgreSQL would be a bit harder as it would require some configuration. If there was a good role on ansible galaxy we could include this however you could also install and configure with custom tasks added in `0.2.4`

**Comment by oxyc** [comment]
I have an ongoing PR for PostgreSQL over at Drupal VM https://github.com/geerlingguy/drupal-vm/pull/490 using https://github.com/ANXS/postgresql. The role seems pretty well tested.

**Comment by thom8** [comment]
Thanks @oxyc 

I've created a PR to add this role. #195

**Comment by thom8** [comment]
Both the `ANXS/postgresql` role and `php5-sqlite` package are now available.

set `installed_extras_postgresql: yes` to enable the postgresql role, other vars maybe required, see the project page for more details -- https://github.com/ANXS/postgresql
