### ISSUE TITLE
Unable to kickstart the project as described in Readme

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#183]
I was trying to follow this:

```
drush dl drupal-8.0.3
cd drupal-8.0.3
vagrant init beet/box
vagrant up
```

And I'm getting this:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Preparing master VM for linked clones...
    default: This is a one time operation. Once the master VM is prepared,
    default: it will be used as a base for linked clones, making the creation
    default: of new VMs take milliseconds on a modern system.
==> default: Cloning VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["clonevm", "4d69b8b5-7f7d-49b9-81ae-f651ccbc66cc", "--register", "--name", "temp_clone_1460376251604_56772"]

Stderr: VBoxManage: error: Could not find a registered machine with UUID {4d69b8b5-7f7d-49b9-81ae-f651ccbc66cc}
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(pszSrcName).raw(), srcMachine.asOutParam())" at line 431 of file VBoxManageMisc.cpp
```

This has been failing on me for a while on different projects. I can fix it only by specifying `v.linked_clone = false` in custom `Vagrantfile`.

**Comment by AlexSkrypnyk** [comment]
As per @Decipher's suggestion, it seems that this issue is related when a base box master linked clone is removed from the `~/.vagrant` directory.

The following code resolves this issue by disabling linked clones by default.

```
  config.vm.provider :virtualbox do |v|
    v.linked_clone = false
  end
```

Looking at this, should linked clones be enabled by default?

**Comment by thom8** [comment]
This issue is caused when the master VM is deleted while the box version is still active.

To rebuild the master VM you need to remove the reference @ `/.vagrant.d/boxes/beet-VAGRANTSLASH-box/[version]/virtualbox/master_id`

This is an upstream issue with vagrant.
