### ISSUE TITLE
Add .beetbox/beetbox.settings.php task

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#190]
To allow for easy management of local site settings in BeetBox it would be nice to have a task/role that adds a check for a `.beetbox/beetbox.settings.php` to the sites installed `settings.php` and if present includes it.

**Comment by Decipher** [comment]
Consensus: Define a `drupal_beetbox_settings` variable which defaults to `.beetbox/beetbox.settings.php` and will add a conditional inclusion to `settings.php` when `drupal_install_site` is `yes`.

**Comment by thom8** [comment]
This would now need to be added to the drupal role -- https://github.com/beetboxvm/ansible-role-beetbox-drupal

Please create PR on this project.
