### ISSUE TITLE
Convert relative paths to absolute

### ISSUE THREAD

**Issue by pendashteh** [beetboxvm/beetbox#191]
When configuring main paths for the project in `config.yml`, if you use relative paths, `beetbox` would not complain and as you expect it would not work.

For example by having this:

```
# Beetbox settings.
beet_project: drupal
beet_domain: "beetbox.local"
beet_root: "docroot"
```

You will have a `vhost.conf` like this:

```
<VirtualHost *:80>
  ServerName beetbox.local
  DocumentRoot docroot

  <Directory "docroot">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
</VirtualHost>
```

A solution will be to convert relative paths to absolute paths basing at `beet_base`.

**Comment by Decipher** [comment]
`beet_root` should be `"{{ beet_base }}/docroot`. We can’t assume that it should be relative from a set point as it’s dependent on the project creators personal requirements.

**Comment by thom8** [comment]
Relative paths aren't supported, please create a PR for review if you need this functionality.
