### ISSUE TITLE
README link to feathub.com is broken

### ISSUE THREAD

**Issue by christopher-hopper** [beetboxvm/beetbox#192]
## Description

The README documentation links to a page for feature requests that returns an Status: 404. 
- http://feathub.com/beetboxvm/beetbox

This is the message returned in the browser:

> The page you were looking for doesn't exist.
> 
> You may have mistyped the address or the page may have moved.
> 
> If you are the application owner check the logs for more information.

**Comment by Decipher** [comment]
Thanks for the issue report. When we changed namespace we must have updated the link but forget to re-import the project on feathub. All done.
