### ISSUE TITLE
Add support for varnish

### ISSUE THREAD

**Issue by nicksantamaria** [beetboxvm/beetbox#193]
This would be very useful when developing applications with more sophisticated caching strategies.

**Comment by thom8** [comment]
@nicksantamaria varnish can be installed by overriding the `installed-extras` var in your `config.yml` - for example 

```
installed_extras:
  - adminer
  - mailhog
  - memcached
  - xdebug
  - xhprof
  - selenium
  - drupal-console
  - varnish
  # - pimpmylog
  # - nginx
  # - nodejs
  # - ruby
  # - solr
  # - redis
```

https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/config/beetbox.config.yml#L154

At this stage you might need to configure the VCL with a custom task.

**Comment by thom8** [comment]
Another option would be to override `varnish_default_vcl_template_path: "{{ beet_base }}/.beetbox/templates/vcl.j2"`, create the file `.beetbox/templates/vcl.j2` and then you can use variables in the VCL.

Here's an example drupal template -- https://raw.githubusercontent.com/geerlingguy/drupal-vm/master/provisioning/templates/drupalvm.vcl.j2

**Comment by thom8** [comment]
@nicksantamaria I've created an example varnish implementation here -- https://github.com/thom8/beetbox/tree/varnish
