### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#200]
To help out newcomers who want to help with BB development we need to provide a document on how to contribute, more specifically:
- How to debug BB locally (including tips and tricks; useful variables etc.)
- How to write tests
- Explicitly state that BB project uses PRs

I personally would like to help with adding new features/refactoring/debugging, but do not clearly understand how to enable BB to read my local config rather than config within the box.

**Comment by thom8** [comment]
Closing in favour of #255
