### ISSUE TITLE
NodeJS role issues

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#207]
It appears that changes in the NodeJS role (upsteam) are affecting the use of the role in Beetbox.

Two specific issues I've run into:

**'ansible_ssh_user' is undefined**

```
==> default: TASK [geerlingguy.nodejs : Define nodejs_install_npm_user] *********************
==> default: fatal: [localhost]: FAILED! => {"failed": true, "msg": "'ansible_ssh_user' is undefined"}
```

This can be resolved be defining that role, but ideally it would be better for this to go back into the Beetbox default config.

**Ensure npm global packages are installed.**

```
failed: [localhost] (item={u'name': u'gulp'}) => {"cmd": "/usr/bin/npm install --global gulp", "failed": true, "item": {"name": "gulp"}, "msg": "npm ERR! tar.unpack untar error /home/vagrant/.npm/gulp/3.9.1/package.tgz\nnpm ERR! Linux 4.2.0-27-generic\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"install\" \"--global\" \"gulp\"\nnpm ERR! node v0.12.14\nnpm ERR! npm  v2.15.1\nnpm ERR! path /usr/lib/node_modules/gulp\nnpm ERR! code EACCES\nnpm ERR! errno -13\n\nnpm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/gulp'\nnpm ERR!     at Error (native)\nnpm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/gulp']\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   path: '/usr/lib/node_modules/gulp',\nnpm ERR!   fstream_type: 'Directory',\nnpm ERR!   fstream_path: '/usr/lib/node_modules/gulp',\nnpm ERR!   fstream_class: 'DirWriter',\nnpm ERR!   fstream_stack: \nnpm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',\nnpm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',\nnpm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /home/vagrant/npm-debug.log", "rc": 243, "stderr": "npm ERR! tar.unpack untar error /home/vagrant/.npm/gulp/3.9.1/package.tgz\nnpm ERR! Linux 4.2.0-27-generic\nnpm ERR! argv \"/usr/bin/node\" \"/usr/bin/npm\" \"install\" \"--global\" \"gulp\"\nnpm ERR! node v0.12.14\nnpm ERR! npm  v2.15.1\nnpm ERR! path /usr/lib/node_modules/gulp\nnpm ERR! code EACCES\nnpm ERR! errno -13\n\nnpm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/gulp'\nnpm ERR!     at Error (native)\nnpm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/gulp']\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   path: '/usr/lib/node_modules/gulp',\nnpm ERR!   fstream_type: 'Directory',\nnpm ERR!   fstream_path: '/usr/lib/node_modules/gulp',\nnpm ERR!   fstream_class: 'DirWriter',\nnpm ERR!   fstream_stack: \nnpm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',\nnpm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',\nnpm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /home/vagrant/npm-debug.log\n", "stdout": "", "stdout_lines": []}
```

This role looks as if it needs to be run as root, but as it's outside of the realm of Beetbox itself that would likely mean a change upstream.

**Comment by thom8** [comment]
@Decipher can you add your specific config for `npm_global_packages`?

All tasks/roles are run as sudo (root) unless specifically set as `become: no`

**Comment by alexdesignworks** [comment]
I've added `nodejs_install_npm_user: "{{ beet_user }}"`, but then got another message:
```
==> beetbox: fatal: [localhost]: FAILED! => {"failed": true, "msg": "'unicode object' has no attribute 'name'"}
```

**Comment by AlexSkrypnyk** [comment]
@thom8 the build passed, but the #2 that @Decipher mentioned still exists. not sure if merged solution actually works. Try adding at least one global package to see whether the build passes.

**Comment by AlexSkrypnyk** [comment]
@thom8 

> All tasks/roles are run as sudo (root) unless specifically set as become: no

Looking at  https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/main.yml#L22, the user is explicitly specified, but should be a user with privileged access rights (root).

**Comment by AlexSkrypnyk** [comment]
```
nodejs_install_npm_user: "root"
nodejs_npm_global_packages:
  - name: gulp
```

This solves #2.
I can still run `gulp` as `vagrant` user with no problems.

**Comment by thom8** [comment]
@alexdesignworks sounds like that's a good workaround but it's not recommended to use root -- https://docs.npmjs.com/getting-started/fixing-npm-permissions

However fixing this would require changes to the role.

Adding this reference -- https://github.com/geerlingguy/drupal-vm/issues/629

**Comment by thom8** [comment]
@alexdesignworks in the mean time there's not really any issue using `root` for a local dev VM, but longterm it would be nice to follow best practice, especially if this role was used in a PROD environment.

Will see if I can put a PR together, but best case it won't be available until the next release.

**Comment by AlexSkrypnyk** [comment]
@thom8 My point was not about using 'root' user (that was just a work around), but was to show that the installation should run as privileged user. 

I do not think that this is an upstream issue as upstream clearly provides the config, i.e. specifying user for which to run installation, and beetbox does not have such non-root user - the only user `vagrant` does not have enough privileges to install node packages globally. So these privileges may need to be added `vagrant`user.
Another demonstration of lack of such privileges for `vagrant` user is ruby role which has exactly the same problem - inability to install gems globally.

**Comment by thom8** [comment]
@alexdesignworks it works with `root` but a global installation shouldn't require `root` (sudo with vagrant user) -- see https://docs.npmjs.com/getting-started/fixing-npm-permissions

I'm fairly confident its an upstream issue and have created a PR here -- https://github.com/geerlingguy/ansible-role-nodejs/pull/28

Also have run into similar issues with composer & ruby, lets fix em?

**Comment by thom8** [comment]
PR merged - https://github.com/geerlingguy/ansible-role-nodejs/pull/28
