### ISSUE TITLE
Update quickstart and default to static IP/auto network plugin.

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#223]
DHCP support with NFS is no longer working, this has unfortunately been very unstable and we aren't able to easily control the delay in boot time. 

The issue is a race condition between the when the VM gets an IP from Virtualbox and the mounting of the NFS shares.

Unless we can resolve the current problem I think it should be removed and we default to vagrant-hostsupdater/vagrant-autonetwork.

Note that we won't remove support for DHCP.

**Comment by Decipher** [comment]
Yes, I generally get it working 1 out of 3 times, which is a pain.

**Comment by thom8** [comment]
Fixed in https://github.com/beetboxvm/beetbox/commit/3ace60e33ceb8eed9ab6be28b552b5b267131e60
