### ISSUE TITLE
Add NFS mount options

### ISSUE THREAD

**Issue by ivangrynenko** [beetboxvm/beetbox#242]
Feature request
Consider adding NFS mount options to speed up NFS share for large projects as per https://www.jverdeyen.be/vagrant/speedup-vagrant-nfs/, namely 
config.vm.synced_folder "./", "/var/www/", type: "nfs",  mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=2'] in Vagrantfile

**Comment by Decipher** [comment]
+1 for this. I have brought this up previously, but evidently never opened an issue.

**Comment by thom8** [comment]
This can be currently achieved in a `Vagrantfile.local` but happy to accept a PR so it can be managed in config.

*note - these mount options conflict with windows so shouldn't be a default.

**Comment by Decipher** [comment]
IIRC, it is possible to specify mount options per OS, so it shouldn't be a massive issue to get the correct mount options in by default without conflicting with windows.

**Comment by thom8** [comment]
As there's nothing stopping you from using that with a local Vagrantfile - please create a PR if you want this to be configurable.

**Comment by thom8** [comment]
@ivrh added docs of how to do this -- http://beetbox.readthedocs.io/en/latest/configuration/vagrant/Vagrantfile.local/
