### ISSUE TITLE
Hostname: localhost or 127.0.0.1 or url-that-is-generated-by-beetbox

### ISSUE THREAD

**Issue by purencool** [beetboxvm/beetbox#245]
After  vagrant provisioning  Beetbox on my Ubuntu 16.04 desktop host, I was faced with the information below. So I went to MySQL Workbench added 127.0.0.1 as the host to get a connect to the MySQL server. But it would not work and kept saying there was no connection. But when used beetbox.local as the  server connection it worked perfectly without an issue.

Could we add some text that says **Hostname: localhost or 127.0.0.1 or url-that-is-generated-by-beetbox**. For someone trying Beetbox for the first time, this could help with the confusion.

```
==> beetbox: MySQL
==> beetbox: ------------------------------------------------------------
==> beetbox: Hostname: localhost or 127.0.0.1
==> beetbox: Port: 3306
==> beetbox: Database name: beetbox
==> beetbox: Username: beetbox
==> beetbox: Password: beetbox
==> beetbox: 
==> beetbox: Drupal
```

**Comment by Decipher** [comment]
@purencool MySQL should only be accessed via SSH (which should maybe made a bit clearer), so what the hostname is referring to is the hostname you need to connect to from within the Vagrant box.

What you need is a Sequel client that supports SSH access (Like SequelPro on Mac), and all the above credentials are in fact correct, but they will also need the SSH details (url-that-is-generated-by-beetbox, etc)

**Comment by thom8** [comment]
@Decipher since the firewall role is now disabled by default you can connect directly to the VM, but would still recommend using SSH.
