### ISSUE TITLE
Docs overhaul required

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#255]
The project has changed quite a bit since the docs were last updated.

Would it be easier if it was outside the repo google docs? or a separate repo for docs?

**Comment by AlexSkrypnyk** [comment]
By default, we should submit changes to docs in PRs together with any code changes. I would prefer to still have docs in this repo.

**Comment by christopher-hopper** [comment]
Having myself submitted updates to Docs on a few projects, including this one, the general pattern I'm seeing is to keep all documentation within the main project, much as you're already doing: under the root path `./docs`. 

I do think that we should add a `.github/CONTRIBUTING.md` that links to `http://beetbox.readthedocs.io/en/stable/contributing/contributing/` and a `.github/PULL_REQUEST_TEMPLATE.md` that looks something like:

```
## Proposed Changes

- 
- 

## Issues

- 

## Notify

@beetboxvm/TEAM
@octocat

```

**Comment by AlexSkrypnyk** [comment]
@christopher-hopper Could you please submit a PR with PR template and a link to contributing page?

**Comment by benjy** [comment]
Are the current docs still outdated? When you run the composer require command documented you only get the Vagrantfile in your project root, not the .beetbox folder or a default/sample config.yml file.

You can manually copy the config file from the vendor folder but then you get errors like the following when trying to provision. Disabling beet_debug was the fix there.
    
    * The host path of the shared folder is missing: ./provisioning

**Comment by AlexSkrypnyk** [comment]
@benjy 
`.beetbox` directory should appear after first `vagrant up`

**Comment by benjy** [comment]
Ah i see, so you have to vagrant up, customise and then re-provision to get the changes picked up.

**Comment by AlexSkrypnyk** [comment]
@benjy yeah, this is how it currently works - composer proxies configuration mapping, but does not repeat what beetbox role does. Maybe, in the future, this can be changed to have all the logic happening in the composer package, or at least creation of `.beetbox` directory.

However, you may not need to create `.beetbox` at all as configuration can be done through `extra` parameter in the `composer.json` and then you may ignore `.beetbox` and `Vagrantfile` using `.gitignore`.

Consider this example:
```
{
  "name": "...",
  "description": "...",
  "require": {},
  "extra": {
    "beetbox": {
      "beet_domain": "local.yoursite.com",
      "beet_root": "{{ beet_base }}/docroot",
      "php_version": "5.6",
      "vagrant_memory": "2048",
      "php_memory_limit": "512M",
      "installed_extras_phantomjs": true,
      "phantomjs_webdriver": true
    }
  }
}
```

**Comment by thom8** [comment]
@benjy any `vagrant` command will generate the `.beetbox` directory & default `config.yml` if it doesn't exist, for example `vagrant status`.

Also here's an example project which uses `composer.json` for all config - https://github.com/thom8/drupal8-vagrant, ignoring both `Vagrantfile` & `.beetbox`

@alexdesignworks [this](https://github.com/beetboxvm/beetbox/blob/master/composer/src/Plugin.php#L52) could be extended to create the default config, which would be useful if we look to add docker support without vagrant.

**Comment by benjy** [comment]
@thom8 thanks for the example, very helpful.

**Comment by thom8** [comment]
@benjy nw here's another example I've knocked up for the Sydney Drupal meetup -- https://github.com/thom8/drupal-sydney-meetup

More of a complete example of a project integration based on the Drupal composer project.

This installs a `config_installer` profile but you could change the composer scripts to pull down a DB.
