### ISSUE TITLE
vagrant provision fails

### ISSUE THREAD

**Issue by SamStamport** [beetboxvm/beetbox#273]
I am following the instructions at http://beetbox.readthedocs.io/en/latest/ - Drupal Quickstart. I modified config.yml instead of using Drush, etc. 

Vagrant provision fails with these messages at the end. How do I fix this?

My site is Drupal Version 7. Is this causing the problem?

"You are about to DROP all tables in your 'beetbox' database. Do you want to co
ntinue? (y/n): y", "stdout_lines": ["You are about to DROP all tables in your 'b
eetbox' database. Do you want to continue? (y/n): y"], "warnings": []}[0m
==> beetbox:    to retry, use: --limit @/beetbox/provisioning/ansible/playbook-pro
vision.retry
==> beetbox: 
==> beetbox: PLAY RECAP ********************************************************

---

==> beetbox: [0;31mlocalhost[0m                  : [0;32mok[0m[0;32m=[0m[
0;32m158[0m  [0;33mchanged[0m[0;33m=[0m[0;33m1[0m    unreachable=0    [0
;31mfailed[0m[0;31m=[0m[0;31m1[0m  
vagrant : The SSH command responded with a non-zero exit status. Vagrant
At line:1 char:1
- vagrant provision
- ~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (The SSH command...status. Vagrant 
    :String) [], RemoteException
  - FullyQualifiedErrorId : NativeCommandError

assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by thom8** [comment]
@ColumbiaBlooms are you using this for an existing site?

If so you'll want to remove -- `drupal_install_site: yes` (default is no) and then import the database after the VM has been provisioned.

**Comment by SamStamport** [comment]
Yes. I'm using my local, dev site. 

Thanks for your prompt reply. I'll give it a try.

**Comment by thom8** [comment]
No worries, it does look like there's an issue with `drush si` & D7

```
vagrant@drupal-7-x-dev:/var/beetbox$ drush si
You are about to DROP all tables in your 'beetbox' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                                                                                         [ok]
sh: 1: /usr/sbin/ssmtp: not found
WD mail: Error sending e-mail (from admin@example.com to admin@example.com).                                                                                                                                                                                         [error]
Installation complete.  User name: admin  User password: F8jC4yrbDs                                                                                                                                                                                                  [ok]
Unable to send e-mail. Contact the site administrator if the problem persists.                                                                                                                                                                                       [error]
```

This relates the the Drupal project role - https://github.com/beetboxvm/ansible-role-beetbox-drupal so will close this and open a new issue against that project.
