### ISSUE TITLE
Automate releases?

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#288]
As this project is capable of continuous delivery, I'd like to introduce automated releases so a new release is made from the current state of master at a regular interval.

Would like some feedback on this regularity 1 month? 2 weeks?

There's always the option of using `beet/dev` if your project requires the latest version for any reason.

**Comment by AlexSkrypnyk** [comment]
IMO, 1 month feels like a reasonable timeframe. Anything more often may be a bit interruptive for users (imagine a team of devs updating a box each 2 weeks for each project).

**Comment by thom8** [comment]
Managed to get a [serverless](https://serverless.com/) app running today that can create automated releases, which would make this project "fully" automated.

It will only create `patch` releases so `major` & `minor` minor releases.

Will do a bit more testing on my fork, but I'm thinking of it running it every 2 weeks.

@alexdesignworks there's no reason you *need* to update to the latest `patch` release, only if you'er running into issues that have been resolved in the latest.

1 month feels a bit long to wait for minor fixes to flow through to a current release.
Anyway we can easily adjust if it is too much.

Also, have another app that can do nightly builds so we can catch any issues before the auto releases run.

**Comment by thom8** [comment]
![image](https://cloud.githubusercontent.com/assets/331453/26297573/c9ed3a8e-3f16-11e7-9138-80efd391c9c6.png)

All done, `dev` will target my fork & `prod` will target this project.

Rather than scheduling the releases statically with a cron, the function will run once a day and only create a new patch release if it has been 14 days since the last one, so we can still create out of band releases.

The nightly function will trigger a CI build of `master`
