### ISSUE TITLE
Ability to add config via Environment variables.

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#292]
It would be nice to have an Environment variable that could be used to specify additional config files to be used during the provision stage.

Use case is CI, where we would want to specify a seperate database server, and potentially remove some unnecessary configuration.

**Comment by thom8** [comment]
I currently use `local.config.yml` for this purpose so in CI another file `ci.config.yml` is moved and renamed to `local.config.yml` to override all other vars, but we could add more override files or add another var to customise the location of a custom override file.

As long as it's ignored by default there's very little risk here.

**Comment by Decipher** [comment]
Yeah, that's exactly what I'm currently doing.

It could also be done as an argument to `beetbox.sh`, something like `beetbox.sh --config[] .beetbox/ci.config.yml` or similar.

Will play more later and try to put a PR together.

**Comment by thom8** [comment]
This can be done by injecting config via `local.config.yml`, using a custom playbook or even overriding the provisioning step with a `Vagrantfile.local`.
