### ISSUE TITLE
Ability to override playbooks.

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#293]
It would be nice if we could supply our own overridden playbooks in `.beetbox/playbooks` that will be copied over the top of the default ones (if the name matches) before the playbooks are provisioned.

This would allow a slimline provisioning playbook to be used that could cut down on provisioning time. The obvious downside is that it has to be maintained by the individual instead of the community, but that would an acceptable tradeoff for those likely to use it.

It would also be nice if something like this could be done via a custom task that is triggered outside of the playbooks, so a user could choose what to move into place under what circumstances.

**Comment by thom8** [comment]
Fixed via #298
