### ISSUE TITLE
Support arguments in beetbox.sh

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#303]
https://github.com/beetboxvm/beetbox/blob/master/provisioning/beetbox.sh

Would like the ability to pass an arg to this script to only run a single playbook.

eg. `beetbox.sh provision` would run `playbook-provision.yml` and any additional args should pass through to `ansible-playbook`

**Comment by Decipher** [comment]
I'd say single or multiple, as generally you want to run the config and update playbooks before the specific playbook.

**Comment by thom8** [comment]
config should probably run before any playbook as there probably would never be a case where you wouldn't want the latest config applied and this is very fast.

Maybe the update playbook could now be combined with config.

**Comment by thom8** [comment]
Addressed in #303 & #321
