### ISSUE TITLE
Make it possible to build the box with working copy instead

### ISSUE THREAD

**Issue by lsolesen** [beetboxvm/beetbox#312]
I build a box using D7 version make files. It would be great if, if there was an option, so the git working copy is checked out, so it was possible to work directly on the modules which is included using a git-repository like you can do with drush --working-copy

**Comment by Decipher** [comment]
You can pass the `working-copy` flag into the makefile itself: http://drupal.stackexchange.com/questions/3829/drush-make-removes-git-folders

**Comment by lsolesen** [comment]
Ok. However, this is not desired for my production sites, so would be nice
with this option in beetbox. A good workaround though.

**Comment by lsolesen** [comment]
Also it seems that I need to do it on project basis - and not for all of the repositories fetched from git.

**Comment by thom8** [comment]
@lsolesen this would require rewriting the makefile, which would be difficult to do in a generic way.

Perhaps you could have a separate makefile for dev or create this dev make file from a template with a custom pre task -- http://beetbox.readthedocs.io/en/latest/configuration/ansible/custom-tasks/

http://docs.ansible.com/ansible/template_module.html

**Comment by lsolesen** [comment]
Ok. I thought it would be as simple as adding the --working-copy flag to
the drush command when using drush.

**Comment by thom8** [comment]
Its a bit hacky but you could append any custom args to `drupal_makefile_path` which would be passed to the drush make command --

https://github.com/beetboxvm/ansible-role-beetbox-drupal/blob/master/tasks/build-makefile.yml#L11

**Comment by thom8** [comment]
This issue relates to the Drupal project role so if you'd like any changes please post issues/PRs there -- https://github.com/beetboxvm/ansible-role-beetbox-drupal
