### ISSUE TITLE
Welcome template require geerlingguy.mysql role

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#314]
Without the `geerlingguy.mysql` role the provisioning welcome template task will fail as it expects the `mysql_port` fact to be set.

Should probably wrap it with a conditional or use a default.

**Comment by thom8** [comment]
Might be easier to just set a default in `beetbox.config.yml`

**Comment by Decipher** [comment]
I just use the `setfact` task to get around it personally, but yes, config works too.
