### ISSUE TITLE
Setting the PHP memory via config

### ISSUE THREAD

**Issue by lsolesen** [beetboxvm/beetbox#318]
Is it possible to set the PHP memory limit using config.yml somehow?

**Comment by thom8** [comment]
Yep you can use the `php_memory_limit` var for example --> https://github.com/beetboxvm/beetbox/blob/master/.beetbox/config.yml#L18

Any variable inside any role can be overridden in your `config.yml` so any of these variable can be added for PHP -- https://github.com/geerlingguy/ansible-role-php/blob/master/defaults/main.yml

**Comment by thom8** [comment]
You'll just need to be mindful that we already override some of the role defaults in the project -- https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/config/profiles/beetbox.config.yml#L155-L219

However, any var in your `config.yml` will override the project defaults.
