### ISSUE TITLE
Allow config/update playbooks to be skipped.

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#323]
For the sake of CI (or other potential usecases), the config and update playbooks only need to be triggered once (as a dependency) rather than at the beginning each of the subsequent playbooks (build, test, deploy).

The addition of a `--skip-setup` (or similar) flag to `beetbox.sh`, which in turn can be set via the appropriate environment, as well as the ability to only run them directly (`BEET_PLAY=config BEET_SKIP_SETUP=true vagrant provision`?) would allow each playbook to be split out into it's own step in CI runners like Circle, making debugging easier.

**Comment by thom8** [comment]
@Decipher we should look at breaking up the Vagrant provisioning -- https://github.com/beetboxvm/beetbox/blob/master/.beetbox/Vagrantfile#L139-L148

so there'd be a provisioning tasks for config, updates and provisioning.
