### ISSUE TITLE
Default to DHCP/0.0.0.0

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#33]
With Avahi having been added, and the updated Vagrantfile supporting plugin-less DHCP networking via Avahi for mac/*nix hosts and a fall back to the previously used plugins for Windows hosts, is there any valid reason not to default to DHCP/0.0.0.0?

**Comment by thom8** [comment]
My preference is that we change the default setting in the Vagrantfile -- https://github.com/drupalmel/beetbox/blob/master/Vagrantfile#L19 but leave the static IP inside the config.yml

This way we know the default settings work on all platforms without the need for plugins which are very flakey on Windows hosts.

As the default would be `DHCP/0.0.0.0` this could be removed for other projects.

**Comment by Decipher** [comment]
Sure, seems like a reasonable compromise.

**Comment by Decipher** [comment]
Done.
