### ISSUE TITLE
Beetbox and Drupal 8

### ISSUE THREAD

**Issue by lsolesen** [beetboxvm/beetbox#338]
I've successfully put beetbox to work for several Drupal 7 sites, but I cannot quite figure out how to do it for Drupal 8. 

I've tried this: https://github.com/motionsplan/motionsplan-d8, but end up with this error:

```
==> beetbox: fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=motionsplan-d8.local", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://beetbox:beetbox@localhost/beetbox"], "delta": "0:00:00.287661", "end": "2016-10-16 20:53:02.358177", "failed": true, "rc": 1, "start": "2016-10-16 20:53:02.070516", "stderr": "Command site-install needs a higher bootstrap level to run - you will    [error]\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'site-install standard' could not be executed.         [error]", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by thom8** [comment]
You'll need to update `beet_root` to the directory of the Drupal install -- https://github.com/motionsplan/motionsplan-d8/blob/migrate/.beetbox/config.yml#L7

In this case it would be `web` rather than `docroot`

**Comment by lsolesen** [comment]
Thanks. However still same problem. My first D8 project, so maybe I messed
up what has been committed to /web?

Den man. 17. okt. 2016 08.29 skrev Thom Toogood notifications@github.com:

**Comment by thom8** [comment]
@lsolesen give this a go -- https://github.com/motionsplan/motionsplan-d8/pull/1

All composer dependencies need to be installed before the drush install.
Also removed `services.yml` & `settings.php` which are created during the install.

**Comment by lsolesen** [comment]
Thank you so much. That fixed it, and I am ready to develop my D8 site :)
