### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lsolesen** [beetboxvm/beetbox#343]
When running drush commands in my beetbox here https://github.com/vih/vih-build, I am getting a segmentation fault. I've haven't tried this before, so I am not really where to start debugging? 

It is on MacOS.

**Comment by thom8** [comment]
@lsolesen this is unlikely a beetbox specific issue and recently the most common reason I've seen this error relates to node -- http://drupal.stackexchange.com/questions/126880/how-do-i-prevent-drupal-raising-a-segmentation-fault-when-using-a-node-js-themin

You may get more info on Drupal answers searching for other common reasons for this error.

**Comment by thom8** [comment]
Closing this for now as it can't be replicated on a default build, reopen if there's anymore information.

**Comment by danepowell** [comment]
We're also seeing segfaults recently, I wonder if it's the same root cause: https://github.com/beetboxvm/beetbox/issues/469
