### ISSUE TITLE
Windows 7 UTF-8 invalid mulibyte char on fresh install

### ISSUE THREAD

**Issue by joelpittet** [beetboxvm/beetbox#347]
I'm testing out this for windows to see how it runs and I'm not a windows user.  **Vagrant 1.8.7** and **VirtualBox 5.1.8**

Tried from PowerShell and Cmder with the same results. 

```
{ beetbox }  » vagrant up                                           /c/Users/Joel/Servers/beetbox
There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

C:/Users/Joel/Servers/beetbox/Vagrantfile:1: invalid multibyte char (UTF-8)
```

DrupalVM seems to get a bit further with the download zip package.

**Comment by thom8** [comment]
@joelpittet What version of Windows are you using? also would you mind posting a copy of the Vagrantfile @ `C:/Users/Joel/Servers/beetbox/Vagrantfile`

Also would recommend updating Vagrant to at least `1.8.6`

**Comment by joelpittet** [comment]
@thom8 I'm using Windows 7 Enterprise edition.  The vagrantfile is https://github.com/beetboxvm/beetbox/blob/master/Vagrantfile  

Vagrant should have been the latest because I just installed it, but maybe there was something left over. I'll check when I get back to work.

**Comment by joelpittet** [comment]
@thom8 My mistake, checked this morning and I am using **Vagrant 1.8.7** not .2.  Updating my initial report

**Comment by joelpittet** [comment]
Whoops this is my issue, when I used wget in PowerShell it needs `-OutFile` `http://superuser.com/questions/362152/native-alternative-to-wget-in-windows-powershell

`wget https://raw.githubusercontent.com/beetboxvm/beetbox/master/Vagrantfile -OutFile Vagrantfile`

A bit to used to wget in unix
