### ISSUE TITLE
How to access xhprof on beetbox?

### ISSUE THREAD

**Issue by Benjen** [beetboxvm/beetbox#356]
Is it possible to use xhprof using the standard beetbox VM? I have seen it appear in the provisioning output, but am not clear how to actually access it on the running VM.

**Comment by thom8** [comment]
@Benjen if your using Drupal I'd recommend the XHProf module -- https://www.drupal.org/project/xhprof which has it's own UI.

Otherwise, you'd need to setup another virtualhost to expose the default XHProf UI, by default this is at `/usr/share/php/xhprof_html`

**Comment by Benjen** [comment]
Thanks, that solved it.
