### ISSUE TITLE
Add project to packagist

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#364]
Would be nice to be able to add `beetbox` as a composer dependency.

As a start it could include a simple installer script which just adds the project `Vagrantfile` to the project root.

This could be extended to create the config directory and include "profiles" via composer extras.
for example : 

```
"extra": {
  "beetbox": {
      "profile": "acquia"
  }
}
```

or potentially add custom config via `composer.json` ...

**Comment by pendashteh** [comment]
Finally!
@thom8 we already have "beet" on packagist if you want to use it.

**Comment by thom8** [comment]
Fixed via #365
