### ISSUE TITLE
Warnings for missing PRE and POST tasks directory

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#369]
## Problem/Motivation

During provision of fresh project, the following messages appear:
```
==> beetbox:  [WARNING]: Unable to find '/var/beetbox/.beetbox/tasks/pre' in expected paths.

.....

==> beetbox: [WARNING]: Unable to find '/var/beetbox/.beetbox/tasks/post' in expected
==> beetbox: paths.
```

## Expected behaviour

Not having these messages shown if either `/var/beetbox/.beetbox/tasks/pre` or `/var/beetbox/.beetbox/tasks/post` directories exist.

## Actual behaviour

As described.

## Steps to reproduce

```
mkdir bb-test && cd bb-test
composer require --dev beet/box
vagrant up
```

## Proposed changes

Add a check for existence of the directories before inclusion.

**Comment by thom8** [comment]
Fixed via #370

**Comment by conantran** [comment]
Hello,

I ran into this issue on macOS Sierra (see screenshot)

```
==> beetbox:  [WARNING]: Unable to find '/var/beetbox/.beetbox/tasks/post' in expected paths
```

<img width="765" alt="screen shot 2017-09-18 at 3 05 42 pm" src="https://user-images.githubusercontent.com/10159742/30529670-1ad1b64a-9c83-11e7-8292-3f59f7b64a8a.png">

**Comment by thom8** [comment]
@conantran this is just a warning as you don't have any custom post provisioning tasks.
