### ISSUE TITLE
Ansible 2

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#37]
So Ansible 2.0.0 is out now, and as such it is breaking our builds.

I suggest we implement a quickfix of enforcing Ansible 1.x until we are ready to update to 2.x.

**Comment by Decipher** [comment]
Fix for testing has been implemented: ffaccc1ce911820edf1374098924c767412f477f

Set version in packer templates has been made as a PR: https://github.com/thom8/packer-templates/pull/1

There's an active fix in the works for the ansible-galaxy issue: https://github.com/ansible/ansible/issues/13419

Once all that is dealt with we need to start testing that all roles/tasks are 2.x compliant and then upgrade.

**Comment by Decipher** [comment]
While the update to the packer template worked on a previous test, it no longer works, implying that they have actually removed the old version from apt... will look into it further.

**Comment by Decipher** [comment]
As I suspected, 1.9.4 had been removed from the apt repo, so I opted to change the packer template to us PIP to install it, which is how the Tests are currently doing it.

I also tested Ansible 2.0.0.1 and experienced hanging on the Galaxy stuff, so I suspect there is more work to be done before we can update to Ansible 2.x.

**Comment by thom8** [comment]
Fixed in #77
