### ISSUE TITLE
Ubuntu 16.10: No guest IP was given to the Vagrant core NFS helper.

### ISSUE THREAD

**Issue by klonos** [beetboxvm/beetbox#387]
## Problem/Motivation

Have tried with stock vagrant, virtualbox packages that come with Ubuntu 16.10 via `apt-get install` (1.8.5 and 5.1.6 respectively) and also with latest versions of Vagrant (1.9.1) and vBox (5.1.14) downloaded from their official websites. I also tried installing the `vagrant-vbguest` vagrant plugin in case this was due to vBox vs Guest Additions version mismatch. Still the same error upon `vagrant up`:

```
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

If I do `vagrant ssh` I see that the VM does get an IP and I am able to ping it from the host and visa-versa.

## Expected behaviour

The VM should be getting a hostname and I should be able to get my local dev loaded on the browser.

## Actual behaviour

The VM does not get a hostname

## Steps to reproduce

1. Fresh installation of Ubuntu 16.10 x64 Desktop
1. `apt-get install composer`
1. `apt-get install vagrant`
1. `apt-get install virtualbox`
1. `vagrant plugin install vagrant-hostsupdater`
1. `vagrant plugin install vagrant-auto_network`
1. `cd` to your project's docroot (I personally `git clone`'d one)
1. `composer require --dev beet/box`
1. `vagrant up`

## Proposed changes

N/A

**Comment by thom8** [comment]
@klonos this issue is usually due to a race condition with the `vagrant-auto_network` plugin & NFS.

Generally, for better stability I'd recommend setting a static IP, which can be anything that doesn't conflict with your local network eg.

in config.yml set
```
vagrant_ip: 192.168.88.88
```

https://github.com/beetboxvm/beetbox/blob/master/.beetbox/config.yml#L3

**Comment by thom8** [comment]
@klonos how did you get on?

Will close this issue for now but you can reopen if you're still having issues.

**Comment by klonos** [comment]
@thom8 sorry for the late reply, I somehow missed your previous comment. I actually needed to get my environment up and running so I gave up on Ubuntu and set it up on Mac. Will return to this issue to do more testing most likely this weekend when I have time. I'll post back here to let you know how it goes, but the point is to eventually get DHCP working so that config tweaking is kept to a minimum.

**Comment by thom8** [comment]
@klonos no worries, I think this is unfortunately an upstream issue - https://www.google.com/search?q=No+guest+IP+was+given+to+the+Vagrant+core+NFS+helper&oq=No+guest+IP+was+given+to+the+Vagrant+core+NFS+helper&aqs=chrome..69i57j69i61j69i59j69i61l2.1059j0j7&sourceid=chrome&ie=UTF-8

however possibly isolated to `ubuntu 14.04`..

Let me know if you find a more stable default configuration, I prefer not adding extra config but a static IP also means less conflicts with updating the hosts file & NFS exports.

**Comment by klonos** [comment]
>Let me know if you find a more stable default configuration...

Yep, will do. We are using beetbox and onboarding was sort of hell because of this (took me so many days trying to figure this out, which made me feel the stupidest I've ever felt in my life - not to mention having to switch to Mac OS). If I get to the bottom of this, I'll be updating our documentation for people that use latest Ubuntu as their local dev env (host OS).

Thanx for this project. A true time saver (...when one gets it to work that is) 😄
