### ISSUE TITLE
EOL PHP support

### ISSUE THREAD

**Issue by ivangrynenko** [beetboxvm/beetbox#389]
## Problem/Motivation

To support EOL application migration, requiring PHP 5.1, PHP 5.2, PHP 5.3

## Expected behaviour

Able to select EOL PHP version

## Actual behaviour

vagrant provision fails when `php_version: "5.3"`

## Steps to reproduce

Add `php_version: "5.3"` to local.config.yml and `vagrant provision`

## Proposed changes

Allow old EOL versions of PHP

**Comment by thom8** [comment]
@ivrh support would need to be added upstream we are using this role for PHP install and config.

https://github.com/geerlingguy/ansible-role-php

It does support installing from source -- https://github.com/geerlingguy/ansible-role-php#installing-from-source

**Comment by ivangrynenko** [comment]
@thom8 
Is there a way to set environment variables without adding new task to the tasks/main.yml?
While compiling custom PHP, I get an error 
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": "./buildconf --force", "delta": "0:00:00.025029", "end": "2017-02-21 04:24:10.776416", "failed": true, "rc": 2, "start": "2017-02-21 04:24:10.751387", "stderr": "make: *** [buildmk.stamp] Error 1", "stdout": "Forcing buildconf\nbuildconf: checking installation...\nbuildconf: You need autoconf 2.59 or lower to build this version of PHP.\n           You are currently trying to use 2.69\n           Most distros have separate autoconf 2.13 or 2.59 packages.\n           On Debian/Ubuntu both autoconf2.13 and autoconf2.59 packages exist.\n           Install autoconf2.13 and set the PHP_AUTOCONF env var to \n           autoconf2.13 and try again.", "stdout_lines": ["Forcing buildconf", "buildconf: checking installation...", "buildconf: You need autoconf 2.59 or lower to build this version of PHP.", "           You are currently trying to use 2.69", "           Most distros have separate autoconf 2.13 or 2.59 packages.", "           On Debian/Ubuntu both autoconf2.13 and autoconf2.59 packages exist.", "           Install autoconf2.13 and set the PHP_AUTOCONF env var to ", "           autoconf2.13 and try again."], "warnings": []}`

**Comment by thom8** [comment]
@ivrh I don't think so, a custom task would be required.

Would also recommend testing it all manually before exporting it to config.
