### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#39]
With lots of different things that can be done with Beetbox it is imperative that we get some good documentation going or no one will know how to use the box.

**Comment by Decipher** [comment]
RTD page has been created: http://beetbox.rtfd.org

**Comment by Decipher** [comment]
Anyone wishing to contribute to the much needed documentation for this project can do so via the following Google Doc:

https://docs.google.com/document/d/1ofGwemvHDDY9AF8XVehrwSWTBUBfS1py21B1kx1i4jE/edit?usp=sharing

Please ensure that you are using the “suggesting” mode when editing.

**Comment by Decipher** [comment]
Re-assigning to 0.3.0 as this is an ongoing task.

**Comment by AlexSkrypnyk** [comment]
@Decipher Can this be closed as first version has been published. Any ongoing tasks will require PRs and there is no point to have non-actionable issue opened.

**Comment by thom8** [comment]
Agreed, this will be an ongoing task throughout the life of the project.
Specific issues can be created to address specific gaps in documentation.
