### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#40]
The number of new functionalities is constantly growing, but the automated testing is very rudimentary; currently it really only tests if it builds successfully, not if things work as expected.

I personally don't have much experience with automated testing outside of web based/PHP stuff, which isn't much use in this case, so I'm open to suggestions.

**Comment by AlexSkrypnyk** [comment]
I have experience around testing infrastructure. Ir is usually using 'bats'
testing framework.

**Comment by Decipher** [comment]
I assume you are referring to https://github.com/sstephenson/bats?

Looks good enough to me. Will wait for @thom8 to way in when he's back online.

We'll also want to ensure that their are multiple different tests jobs run per each different project. Hopefully we can leverage cache for that so that we don't need to do a full build for each different project given that the current test already takes upwards of 10 minutes.

**Comment by thom8** [comment]
As it would be insurmountable task to create tests for all possible permutations of the configuration, we need to decide what our testing limits should be.

Most of the roles already have automated tests, and testing ansible modules is probably overkill.

We also need to add some caching to the existing tests so that the apt cache / composer cache etc are preserved between builds.

We also should add a final testing task that will check that the provisioning worked, maybe this could be triggered by an environment variable that we could set on circle CI.

**Comment by AlexSkrypnyk** [comment]
If we are not talking about testing that end-to-end provisioning worked
(because we already have that) and we are not talking about testing roles
(because each role has own build with tests), then it looks like we only
need to test beetbox glue code (if any), which is the same on each branch.

**Comment by Decipher** [comment]
The one thing I'm specifically talking about is the Drush alias; it wasn't working, it was fixed and then broken again. I'm sure that's not the only thing that doesn't have any tests in place at the moment, but it's the only thing I'm aware of. We need to ensure that any of the various things Beetbox can do has tests, it's as simple as that.

**Comment by AlexSkrypnyk** [comment]
Is that alias provisioned by a role? If so, tests should be in role repo.

**Comment by Decipher** [comment]
No, it's provided by the Vagrantfile.

**Comment by AlexSkrypnyk** [comment]
Then it should be in beetbox tests.

However, the fact that beetbox can be used not only for drupal makes it to
have specific tests on specific branches only. And this is weird.
I mentioned to Thom that a branch-based configs are a bit unexpected.

**Comment by Decipher** [comment]
I think the branch based configs should only be considered examples provided by Thom. Ideally I'd like to have something similar to various other opensource projects (mysql, etc), a directory full of example config files that can be copied over config.yml to just get what you want up and running.

If we went down this path, we could just have multiple jobs defined for Circle CI that run concurrently, each grabbing a different config.yml file to test various different usecases.

**Comment by thom8** [comment]
Yeah this would be the best option however if possible I'd like to keep the main test build to ~10mins.

There's also the circle CI option of parallelism - https://circleci.com/docs/parallel-manual-setup
so we could run the base build then split out for the other build configs.

ATM there's no testing coverage of the drupal composer builds because it's not on by default and isn't a seperate galaxy role.

**Comment by thom8** [comment]
How about a new beetbox-tests role which installs vagrant then does a syntax check and runs status to setup the drush aliases.

We could then use stat module to test that the alias is setup and perhaps hack the lineinfile module with a `failed_when` (http://docs.ansible.com/ansible/playbooks_error_handling.html) arg to assert the settings inside the alias file.

This role is triggered by a environment variable that we only set on the circle CI tests.

**Comment by Decipher** [comment]
Testing that the alias is setup doesn't prove that the alias works. The alias has been being setup for quite some time, but it's never actually been connected to the site itself.

We really need to be testing that the alias is setup correctly by running `drush st` and checking the results.

We should also be running similar tests for the different build/install approaches, just because Ansible didn't fail while building a site doesn't mean that the site is actually accessible or installed.

**Comment by thom8** [comment]
Yeah it's probably easier to run a `drush st` and grep for the db connection, then `fail_when` this doesn't exist.

I'm fairly confident that if the install task completes and the web and database servers are restarted successfully the site should be accessible and installed.

We might just need to confirm that the webserver port is open.

**Comment by thom8** [comment]
Here's a starter concept of adding a new tests playbook + role to test services are working for the default build.

https://github.com/thom8/beetbox/blob/beet_tests/ansible/roles/beetbox-tests/tasks/main.yml

**Comment by thom8** [comment]
Tests role added in #122.

We can now add tests to validate bug fixes and new features where possible.

**Comment by thom8** [comment]
http://serverspec.org/ is another option if we find ansible tests are lacking features.

**Comment by AlexSkrypnyk** [comment]
Can this issue be closed as it is a non-actionable issue? The initial test role was added so any future tests would be submitted as separate PRs.

**Comment by thom8** [comment]
Same as #39 --
