### ISSUE TITLE
How to enable wp-cli

### ISSUE THREAD

**Issue by ivangrynenko** [beetboxvm/beetbox#400]
## Problem/Motivation

There is  wordpress support and I can see wp-cli variables. However upon provisioning a new box, I am unable to execute wp-cli tool.

## Expected behaviour

wp or wp-cli works OOTB

## Actual behaviour

wp-cli
wp-cli: command not found
wp
wp: command not found

## Steps to reproduce

Provision new beetbox, vagrant ssh, run `wp`

## Proposed changes

Document the way to have wp-cli installed

**Comment by thom8** [comment]
@ivrh see -- https://github.com/beetboxvm/beetbox/blob/master/.beetbox/config.yml#L85-L91

PR for docs would be good :)

**Comment by thom8** [comment]
Sorry you'll also need `installed_extras_wp_cli: yes` this used to be controlled by `beet_project`
