### ISSUE TITLE
403 Forbidden after vagrant up

### ISSUE THREAD

**Issue by MatthieuScarset** [beetboxvm/beetbox#408]
## Problem/Motivation

> I got a 403 forbidden after `vagrant up`.
> The virtual host is working but the root folder is not correct. 
> http://drupal8.local give a 403 
> http://drupal8.local/web works.

## Expected behaviour

> I expected http://drupal8.local would works and the `web` folder would be the root folder.

## Actual behaviour

> The root folder is not correct.

## Steps to reproduce

> Create the [drupal-project with composer](https://github.com/drupal-composer/drupal-project)
> Add beet/box to composer.json
> Run `vagrant up`

**Comment by MatthieuScarset** [comment]
Anyway to specifiy the root folder in `.beetbox/config.yml` ?

**Comment by thom8** [comment]
@MatthieuScarset yep just set `beet_root: "{{ beet_base }}/web"` and run `vagrant provision` will try to replicate issue now.

**Comment by thom8** [comment]
@MatthieuScarset fixed in `0.5.1` -- building now -- https://circleci.com/gh/beetboxvm/beetbox/523

**Comment by MatthieuScarset** [comment]
Thanks @thom8 

Settings `beet_root` fix the issue on a new vagrant provision

**Comment by thom8** [comment]
@MatthieuScarset classic typo -- https://github.com/beetboxvm/beetbox/commit/154da72ca6e6f1bfb74d6bece5b56d41ebdad6b9

The auto detection should work from `0.5.1`
