### ISSUE TITLE
php-imap is a new requirement?

### ISSUE THREAD

**Issue by ivangrynenko** [beetboxvm/beetbox#412]
When running
composer require --dev beet/box

OS: MacOS 10.12.5 Beta

The following error interrupts the installation. Is this a new dependency on php-imap module?

bash-3.2$ composer require --dev beet/box
Using version ^0.5.1 for beet/box
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-imap/php-imap 2.0.4 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - php-imap/php-imap 2.0.4 requires ext-imap * -> the requested PHP extension imap is missing from your system.
    - Installation request for php-imap/php-imap (installed at 2.0.4) -> satisfiable by php-imap/php-imap[2.0.4].

Installation failed, deleting ./composer.json.

**Comment by thom8** [comment]
@ivrh there's no explicit dependency set in this project -- https://github.com/beetboxvm/beetbox/blob/master/composer.json

I don't have the imap module loaded and it works in a empty directory.

```
Using version ^0.5.1 for beet/box
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing beet/box (0.5.1): Downloading (100%)
Writing lock file
Generating autoload files
```

You could try `composer why php-imap/php-imap`

**Comment by thom8** [comment]
Also recommend checking you have the latest version - `composer selfupdate`
This shouldn't be a requirement tho.

**Comment by ivangrynenko** [comment]
Thanks. The issue resolved, the cause was existing vendors in the docroot folder. I had to rearrange this project, moving it to /docroot/.
