### ISSUE TITLE
OOB Beetbox drush 8.1.12 not compatible with Drupal 8.4.x 

### ISSUE THREAD

**Issue by dabito** [beetboxvm/beetbox#414]
## Problem/Motivation

I have a Drupal core 8.4.x in my beetbox and i can't run drush commands.

## Expected behaviour

drush commands work, for example drush cr all rebuilds all caches

## Actual behaviour

drush commands don't work, issuing any drush command results in fatal error:

`PHP Fatal error:  Declaration of Drush\Command\DrushInputAdapter::hasParameterOption() must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /usr/local/share/drush/lib/Drush/Command/DrushInputAdapter.php on line 27`

## Steps to reproduce

1. Update your drupal to 8.4.x
2. Run any drush commands.

## Proposed changes

I'd like to know how to upgrade drush (tried composer global). A long-term solution may be to add a variable to determine the drush version to be installed (beet_drush_version?).

**Comment by dabito** [comment]
May be related to https://github.com/drush-ops/drush/issues/2474

**Comment by thom8** [comment]
@dabito you can set the drush version with `drush_version`

https://github.com/beetboxvm/beetbox/blob/11f3c8e3a7867b71b2637a0a1d2f08dd413ec396/provisioning/ansible/config/default.config.yml#L243

It may now require `drush_version: "9.x"`

**Comment by thom8** [comment]
@dabito Sorry that should be `drush_version: "master"` there's no `9.x` branch 

-- just updated https://github.com/thom8/drupal8-vagrant/commit/c5bd0385858724d22834c32612f6638adcf545a5

**Comment by thom8** [comment]
It also supports setting a tag -- https://github.com/drush-ops/drush/tags

like `9.0.0-beta1`

**Comment by dabito** [comment]
Thank you so much, @thom8 !
