### ISSUE TITLE
Add support to non-default composer.json

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#420]
## Problem/Motivation
Currently, composer files is assumed to be `composer.json`, but should be read from environment variable `COMPOSER` (https://getcomposer.org/doc/03-cli.md#composer)
```
composer_json = "#{beet_root}/composer.json"
```
## Expected behaviour
Configuration should be read from the composer configuration provided in `COMPOSER` environment variable.

## Actual behaviour
Only `composer.json` is supported.

## Proposed changes
Add support for composer config file with a fallback to the `composer.json`.

**Comment by thom8** [comment]
Fixed in #421
