### ISSUE TITLE
Add Gulp, NVM and Yeoman

### ISSUE THREAD

**Issue by mariohernandez** [beetboxvm/beetbox#441]
## Problem/Motivation

> Would be nice to have Gulp, NVM and Yeoman integrated to facilitate the creation of front-end environments.

## Expected behaviour

> After ssh into vagrant, I could execute gulp tasks for my front-end environment.  This would also allow me to manage the node version to ensure anyone using my fork uses the same version of node using **nvm**

## Actual behaviour

> N/A:  Gulp is missing

## Steps to reproduce

> N/A

**Comment by thom8** [comment]
@mariohernandez you're able to add and NPM global dependencies with the `nodejs_npm_global_packages` variable from the [NodeJS role](https://github.com/geerlingguy/ansible-role-nodejs)

```
nodejs_npm_global_packages:
  - name: gulp-cli
  - name: yeoman
```

This role uses the [nodesource](https://github.com/nodesource/distributions) therefore the `nodejs_version` is limited to the latest major version eg `4.x`, `6.x` there is a suggestion of switching to `nvm` -- https://github.com/geerlingguy/ansible-role-nodejs/issues/27 which would be nice.

Another option is to install a local version of node with something like -- https://github.com/thecodingmachine/nodejs-installer

**Comment by thom8** [comment]
@mariohernandez hope this answered your question, reopen this issue if you have any more queries.
