### ISSUE TITLE
XHProf role requires an internet connection during provision

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#45]
The XHProf role currently requires an internet connection during provision as it tries to install both the PECL channel and package regardless of whether it is already installed (which it is in Beetbox).

As such, it means that anyone trying to provision offline with the defaults (having XHProf role being installed) will not be able to do so.

I have already submitted a PR to the role that will resolve the issue (https://github.com/geerlingguy/ansible-role-php-xhprof/pull/2), but until that PR is accepted we should consider a short-term fix.

The options I can see are:
- Remove XHProf from the defaults
- Apply the PR as a patch to the role
- Use a fork of the role

**Comment by thom8** [comment]
My preference would be to remove xhprof from the defaults until the PR is merged upstream.

**Comment by Decipher** [comment]
Agreed.

However, currently the PR I made for XHProf needs work as it is failing tests; It appears there's a false negative where if no version is detected (eg, it needs to be installed) the test is failing rather than installing XHProf.

**Comment by Decipher** [comment]
Merged a temporary removal of XHProf from the base box (won't come into play until the next build).

Have also updated the PR (https://github.com/geerlingguy/ansible-role-php-xhprof/pull/2) so that it should now pass the tests.

**Comment by oxyc** [comment]
I believe this should be fixed upstream as soon as Centos 6 starts behaving and this PR gets merged: https://github.com/geerlingguy/ansible-role-php-xhprof/pull/12

**Comment by thom8** [comment]
Thanks @oxyc!

@Decipher looks like we can add this back into the defaults.
