### ISSUE TITLE
Existing symfony project setup

### ISSUE THREAD

**Issue by maykino** [beetboxvm/beetbox#452]
Can you please list the exact steps to get an existing symfony application to work with beetbox. It looks like I get the Forbidden 403 error when I try to access the project.

**Comment by thom8** [comment]
Take a look @ https://github.com/beetboxvm/ansible-role-beetbox-symfony/tree/f7fe8067d9aa3681b953574ba4e4593e8d6c65e2 for an example.

Just ran a test build here -- https://circleci.com/gh/beetboxvm/ansible-role-beetbox-symfony/10

**Comment by rwitchell** [comment]
@maykino : in your .beetbox/config.yml, add web as follows:
beet_web: "{{ beet_root }}/{{ symfony_project_name }}/web"

**Comment by thom8** [comment]
Thanks @rwitchell, sorry been overseas and just catching up on issues.

Will move this one over here -- https://github.com/beetboxvm/ansible-role-beetbox-symfony/issues/1
