### ISSUE TITLE
Provide a default for Drush alias root

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#48]
Currently the Drush alias root uses `beet_web`, but if that isn't defined in `.beetbox/config.yml` then it will not work correctly.

We need to set a default/fallback in the Vagrantfile.

I would suggest the default being `/www/docroot` and also using that as the default for the `beet_root` variable.

**Comment by thom8** [comment]
We probably need to update the default to be more generic as some projects the docroot is actually a sub-directory of the project root, for example in a drupal composer build the docroot is inside the web subdirectory.

maybe we could use something like `/var/beetbox` as the default `beet_root`

**Comment by Decipher** [comment]
So if we are going down this route (which I agree with) we will also need to do the following:
- Set a default value for `beet_root` in the Vagrantfile
- Update the synced folder to use the config value instead of the hardcoded `/www` value
- Update `beet_web` default to be `"{{ beet_root }}/docroot"`
- Set a default value for `beet_web` in the Vagrantfile for the sake of the Drush alias root

As for other projects that have a different folder for the docroot, this isn't really all that different to how it already stands, and is as equally configurable, so it shouldn't cause an issue.

I plan to action this task ASAP.

**Comment by Decipher** [comment]
The `beet_web` variable will be different in the default `.beetbox/config.yml` and `Vagrantfile` to keep it more inline with the existing example:
- config.yml: `"{{ beet_root }}/{{ beet_project }}"`
- Vagrantfile: `"{{ beet_root }}/docroot"`

That way we don't need to overcomplicate things with a default `beet_project` in the Vagrantfile, but things will work pretty much the way they already do in the config.yml.

**Comment by thom8** [comment]
I believe #66 has resolved this issue by falling back to `beet_root` or `beet_base` if `beet_web` has not been defined.

https://github.com/drupalmel/beetbox/blob/master/Vagrantfile#L161
