### ISSUE TITLE
beet_site_name should be drupal_site_name

### ISSUE THREAD

**Issue by AlexSkrypnyk** [beetboxvm/beetbox#49]
for consistency, since `beet_site_name` is used only with drush command to install a site.

**Comment by thom8** [comment]
@alexdesignworks it is also used by other roles eg. the wordpress role -- https://github.com/thom8/ansible-role-beetbox-wordpress/blob/master/tasks/main.yml#L32

**Comment by Decipher** [comment]
Yeah, I'd agree that it shouldn't, it's a project agnostic variable. Closing issue.
