### ISSUE TITLE
Enable Upload Progress in Apache / nginx?

### ISSUE THREAD

**Issue by BrianGilbert** [beetboxvm/beetbox#52]
From Drupal report page:

Your server is capable of displaying file upload progress, but does not have the required libraries. It is recommended to install the PECL uploadprogress library (preferred) or to install APC.

http://pecl.php.net/package/uploadprogress
http://us2.php.net/apc

**Comment by thom8** [comment]
This is possible with the following config 

```
php_pecl_extensions:
  - uploadprogress
```

APC is not required with PHP 5.5 and above as it ships with zend opcache.

We need to test this more before adding it by default as I think PECL requires a network connection (even if it is installed already).

**Comment by Decipher** [comment]
Not entirely true. The XHProf role required an internet connection because it wasn't checking if the package was already installed.

**Comment by thom8** [comment]
I can confirm that the `php-pecl` role -- https://github.com/geerlingguy/ansible-role-php-pecl/blob/master/tasks/main.yml attempts to install packages before checking they have been installed so therefore it will fail without a network connection.
