### ISSUE TITLE
Add variable to switch between apache and nginx

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#56]
Rather than having to change ports to make use of nginx, it would be easier to have a `beet_webserver` variable and make all the changes required based on this setting.

**Comment by Decipher** [comment]
Agreed. While I have not yet played with Nginx in beetbox yet, it is something that Brian has asked about and I had planned on looking at in the future. This seems like the right approach.

Alternatively though, maybe a variables for defining the ports of the relevant servers, or a port map?

**Comment by thom8** [comment]
Fixed in #75
