### ISSUE TITLE
Add cache support to circle

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#68]
To speed up test builds.

https://circleci.com/docs/how-cache-works

**Comment by AlexSkrypnyk** [comment]
@thom8 Could you please outline what would you like to cache from BB

**Comment by thom8** [comment]
@alexdesignworks apt packages to begin with but I'd also like to investigate if we could somehow use containers to cache a pre-provisioned build.

**Comment by AlexSkrypnyk** [comment]
>  cache a pre-provisioned build.
> Do you mean for testing? But how would new changes apply?
> I mean, if the box is already provisioned, would you run provisioning again to just provision the changes rather than a whole box from the start?

**Comment by thom8** [comment]
For the main project we use CI to replicate an Atlas build (including its minimisation scripts), then test an initial provision with settings from the main projects `.beetbox/config.yml`.

Therefore we probably want a fresh build for each build but we can cache the APT cache (which will be updated each build) and anything downloaded, as long as version numbers are in the path or name so updates ignore the cache.

However the goal moving forward as mentioned in #151 is to extract most of the roles into their own projects so test coverage can be expanded per project. In this case it would be nice to have a pre-provisioned base image as the sub-projects aren't concerned with the box build but modifications of the current build.

**Comment by thom8** [comment]
Cache dir created in #233
