### ISSUE TITLE
Spit out credentials/URLs at the end of the provisioning step.

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#86]
At the end of the provisioning step it would be nice if important credentials where spat out to simplify things for the user, such as the database user/password/name, the site URL and login details.

**Comment by thom8** [comment]
We could use an ansible template that `ansible/build.sh` prints at the end. -- http://docs.ansible.com/ansible/template_module.html

A dashboard would also be a nice feature --
https://github.com/geerlingguy/drupal-vm/pull/404

**Comment by thom8** [comment]
Fixed by #101
