### ISSUE TITLE
Create beetbox vagrant plugin

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#88]
Kickstarting the idea of creating a vagrant plugin for beetbox that could:

*Prompt for some important config settings and create the config file.
*Automatically create the project Vagrantfile.
*Automatically create a `circle.yml` file so you can test your own implementation then you can potentially add you own project tests scripts.

**Installation**
`vagrant plugin install beetbox`

**Example wordpress init**
`vagrant beetbox init wordpress`

**Comment by thom8** [comment]
If project type is drupal this could then ask for hosting provider and add presets for this..

**Comment by Decipher** [comment]
I think this is a great idea, in addition to the existing auto-magic of the box Vagrantfile, as long as it is not a requirement but an optional addition.

On top of this idea, a simple GUI could leverage this plugin, allowing us an optional GUI for those who need it without the need for duplicating the logic.

**Comment by thom8** [comment]
Working on a Yeoman generator -- https://github.com/thom8/generator-beetbox-drupal

Basically it prompts for config settings (with default values) and generates the `config.yml` & `Vagrantfile` for a new project.

**Comment by thom8** [comment]
Work will continue in this project -- https://github.com/beetboxvm/generator-beetbox
