### ISSUE TITLE
Build box Vagrantfile dynamically

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#94]
Due to the automated build structure set in place for this project there should be no need for duplicate functionality.

The box Vagrantfile could be built dynamically and overrides injected into placeholders if required.

relates to #91 & #65

**Comment by Decipher** [comment]
Possibly, however there is a fairly big difference between the Box Vagrantfile and the default project Vagrantfile, which is the multi-dev functionality, which can not be done in the Box Vagrantfile as the Box Vagrantfile is supposed to be the defaults for any machines using said Box, where as the Multidev is to define multiple machines using said Box.

I had already considered breaking the Box Vagrantfile into smaller ruby components though, for things like Project detection and various different auto-magic components.

**Comment by thom8** [comment]
This might require refactoring the project Vagrantfile into components with placeholders but if they have directly duplicated functionality, which it should in most cases, it will more than likely come back to bite us.

There's no reason why multi-dev functionality couldn't work in the box Vagrantfile.

**Comment by thom8** [comment]
I think the best approach to address both this issue & #96 will be to refactor the deployment process to use ansible.

A deployment can include creating a packer template from an ansible template, building the box Vagrantfile etc, then finally pushing to Atlas.

**Comment by thom8** [comment]
Looks like the checksum has changed in Vagrant `1.8.4` and we'd somehow need to support multiple versions.

Is it still being used? I'm working on a better alternative to the single command setup -- https://github.com/beetboxvm/generator-beetbox

Also there's a better solution to a shared `Vagrantfile` by using the new [Vagrantfile](https://github.com/beetboxvm/beetbox/blob/master/Vagrantfile) and referencing another remote source like a gist which you have control of and can update at will. Even using the project default will always pull in the latest version of master rather than needing to wait for the next release.

**Comment by thom8** [comment]
@Decipher just thinking rather than replicating the `Vagrantfile` we could use the stub inside the box which downloads the project `Vagrantfile` to the `.beetbox` dir.

https://github.com/beetboxvm/beetbox/blob/master/Vagrantfile

and rather than download it directly from GH it could store a copy in the box and download it from there..

**Comment by Decipher** [comment]
The most obvious problem here is that if you try to provision when you are offline, it won't be able to do that from the prepackaged Vagrantfile.

**Comment by thom8** [comment]
The very 1st `vagrant` command even just a `vagrant status` will download the project Vagrantfile.

From then on it will just reference the one in the `/.beetbox` dir.

But if you absolutely need the ability to create new projects offline (this is only required the very first time you init a new project) you could add a version in the box like `Vagrantfile.box` and move it from there into the projects bb dir, this could even be a fall back..

**Comment by thom8** [comment]
The box vagrant file is conflicting with the docker provider as the `Vagrantfile` is optional -- https://www.vagrantup.com/docs/docker/configuration.html#vagrant_vagrantfile

**Comment by thom8** [comment]
Fixed via #265
