### ISSUE TITLE
Nightly tests/builds of dev branch/box.

### ISSUE THREAD

**Issue by Decipher** [beetboxvm/beetbox#98]
Prior to the automated builds, we where running nightly builds of `DrupalMel/beetbox-dev` on Atlas, allowing us to identify changes made beyond our control that had a negative effect on the builds.

Unfortunately due to the change to the versioning pattern we can not continue to do this.

Instead, what we need is to have is a nightly CircleCI trigger, which would, if the test passed, trigger the nightly Atlas builds.

There is documentation on an Experimental feature of CircleCI that will allow for this at https://circleci.com/docs/nightly-builds

**Comment by thom8** [comment]
I think it might be a good idea to rollback to nightly builds rather than building on each commit.

We can normally wait for a new dev box or build manually if required.

**Comment by Decipher** [comment]
I'd say we really need both, especially so we can test with the latest dev box before releasing the next stable release without needing to wait upwards of 24 hours.

**Comment by thom8** [comment]
Doesn't look like this is possible without additional infrastructure and I'm reluctant to introduce anything else that may require ongoing support.

Last build of `beet/dev` is based on the last commit on master.
