### ISSUE TITLE
Move to beet org on Atlas

### ISSUE THREAD

**Issue by thom8** [beetboxvm/beetbox#99]
It could be a bit confusing for beginners to use `vagrant init DrupalMel/beetbox` for a non Drupal project.

I propose that we migrate to the new Atlas beet org -- https://atlas.hashicorp.com/beet

and rename the main box to `box` making the init command --
`vagrant init beet/box`

**Comment by Decipher** [comment]
I'm ok with this. I'd also like a dedicated user for the org as well; beetbox or beetboxvm. That way we can ensure that the CI uses it's token rather than one of ours.

**Comment by thom8** [comment]
Further to this I think it might be a good idea to move this project to it's own GH org.
The primary reason is that we're going to need multiple repo's to manage roles.

As a start I'd like to move these over -- https://github.com/search?q=user%3Athom8+ansible-role-beetbox

I also think we should pull out the `beetbox-drupal` role into its own repo so it can have better testing, eg the drupal composer tasks are not part of the example project and therefore have no test coverage. isolating this into it's own role with it's own tests will allow us to create a dedicated test cases to cover all tasks.

Further reasoning is suggested in #130

**Comment by Decipher** [comment]
`beet/box` = `ef550c44b71ef09513fe24c4b564c8a9`
`beet/dev` = `c704fbc0a4343dcd6778896a150604b5`

**Comment by Decipher** [comment]
Done.
